package com.example.adobongkangkong.domain.planner.usecase

import androidx.room.withTransaction
import com.example.adobongkangkong.data.local.db.NutriDatabase
import com.example.adobongkangkong.data.local.db.entity.PlannedSeriesEndConditionType
import com.example.adobongkangkong.data.local.db.entity.PlannedSeriesEntity
import com.example.adobongkangkong.data.local.db.entity.PlannedSeriesItemEntity
import com.example.adobongkangkong.data.local.db.entity.PlannedSeriesSlotRuleEntity
import com.example.adobongkangkong.domain.planner.model.PlannedItemSource
import com.example.adobongkangkong.domain.repository.PlannedItemRepository
import com.example.adobongkangkong.domain.repository.PlannedMealRepository
import com.example.adobongkangkong.domain.repository.PlannedSeriesItemRepository
import com.example.adobongkangkong.domain.repository.PlannedSeriesRepository
import com.example.adobongkangkong.domain.repository.RecipeBatchLookupRepository
import java.time.LocalDate
import javax.inject.Inject

/**
 * Promotes an existing planned meal into a reusable recurrence series template.
 *
 * ## Definition — Planned series template
 *
 * A planned series represents a reusable recurrence definition that can generate
 * future planned meals automatically (for example: "Chicken Lunch every Mon/Wed/Fri").
 *
 * This use case converts a concrete, already-planned meal into the canonical
 * template representation used by the planner recurrence system.
 *
 * The selected meal becomes the **anchor occurrence** and its contents define:
 *
 * - recurrence schedule (weekday + slot)
 * - template items (foods, recipes, recipe batches)
 * - effective start date
 *
 * Future occurrences are later generated by EnsureSeriesOccurrencesWithinHorizonUseCase.
 *
 * ---
 *
 * ## Why this exists
 *
 * Users commonly create a single planned meal first, then decide to repeat it.
 *
 * Instead of forcing users to rebuild the meal inside a recurrence editor,
 * this use case allows:
 *
 *   "Create once → Promote to series"
 *
 * preserving:
 *
 * - slot (breakfast/lunch/dinner/custom)
 * - weekday pattern
 * - all planned items
 * - order and quantities
 *
 * This improves UX and guarantees exact template fidelity.
 *
 * ---
 *
 * ## What this use case creates (transactional)
 *
 * Within a single database transaction:
 *
 * 1) Creates PlannedSeriesEntity
 *
 *    Defines recurrence metadata and anchor date.
 *
 * 2) Creates PlannedSeriesSlotRuleEntity
 *
 *    Defines recurrence schedule using the anchor meal's weekday and slot.
 *
 * 3) Creates PlannedSeriesItemEntity rows
 *
 *    Copies all planned_items into reusable template items.
 *
 *    Special handling:
 *
 *    FOOD → copied directly
 *    RECIPE → copied directly
 *    RECIPE_BATCH → converted to underlying recipeId
 *
 *    This prevents recurrence from referencing ephemeral batch snapshots.
 *
 * 4) Updates the original PlannedMealEntity
 *
 *    Sets seriesId to mark the meal as part of the series.
 *
 *    This meal becomes the anchor occurrence.
 *
 * ---
 *
 * ## Important: does NOT generate future occurrences
 *
 * This use case ONLY creates the series template.
 *
 * It does NOT expand occurrences into planned_meals.
 *
 * Caller must invoke:
 *
 * EnsureSeriesOccurrencesWithinHorizonUseCase
 *
 * or use CreateSeriesAndEnsureHorizonUseCase wrapper.
 *
 * ---
 *
 * ## Transaction guarantees
 *
 * Entire operation runs inside Room transaction.
 *
 * Either:
 *
 * - series + rules + template items + anchor linkage all succeed
 *
 * OR
 *
 * - nothing is written
 *
 * Prevents partial or corrupt recurrence definitions.
 *
 * ---
 *
 * ## Recipe batch handling rationale
 *
 * Recipe batches represent snapshot foods.
 *
 * Recurrence must reference the underlying recipe, not a specific batch,
 * because batches are time-specific and may be deleted.
 *
 * This use case resolves:
 *
 * RECIPE_BATCH → recipeId
 *
 * ensuring recurrence stability.
 *
 * ---
 *
 * ## Pitfalls / gotchas
 *
 * This does NOT deduplicate series.
 *
 * Caller must ensure meal is not already part of a series if that matters.
 *
 *
 * PlannedSeriesItemEntity.note is currently null
 *
 * planned_items does not store notes yet.
 *
 *
 * Future schema changes must preserve recipeId resolution behavior.
 *
 *
 * This use case assumes PlannedMealEntity.date is valid ISO yyyy-MM-dd.
 *
 *
 * Removing the anchor meal does NOT automatically delete the series.
 *
 * Series lifecycle must be handled separately.
 */
class CreateSeriesFromPlannedMealUseCase @Inject constructor(
    private val db: NutriDatabase,
    private val meals: PlannedMealRepository,
    private val items: PlannedItemRepository,
    private val seriesRepo: PlannedSeriesRepository,
    private val seriesItems: PlannedSeriesItemRepository,
    private val recipeBatchLookup: RecipeBatchLookupRepository,
) {

    data class Result(
        val seriesId: Long,
        val anchorDate: LocalDate
    )

    suspend fun execute(mealId: Long): Result = db.withTransaction {
        val meal = meals.getById(mealId)
            ?: error("PlannedMeal not found: id=$mealId")

        val anchorDate = LocalDate.parse(meal.date)
        val now = System.currentTimeMillis()

        val mealItems = items.getItemsForMeal(mealId)

        // Create series
        val seriesId = seriesRepo.insertSeries(
            PlannedSeriesEntity(
                effectiveStartDate = meal.date,
                effectiveEndDate = null,
                endConditionType = PlannedSeriesEndConditionType.INDEFINITE,
                endConditionValue = null,
                sourceMealId = meal.id,
                createdAtEpochMs = now,
                updatedAtEpochMs = now
            )
        )

        // Slot rule for the anchor meal
        val rule = PlannedSeriesSlotRuleEntity(
            seriesId = seriesId,
            weekday = anchorDate.dayOfWeek.value,
            slot = meal.slot,
            customLabel = meal.customLabel,
            createdAtEpochMs = now
        )
        seriesRepo.replaceSlotRules(seriesId, listOf(rule))

        // Template items
        for (mi in mealItems) {
            val (foodId, recipeId) = when (mi.type) {
                PlannedItemSource.FOOD -> mi.refId to null

                PlannedItemSource.RECIPE -> null to mi.refId

                PlannedItemSource.RECIPE_BATCH -> {
                    val batch = recipeBatchLookup.getBatchById(mi.refId)
                        ?: error("Recipe batch not found: batchId=${mi.refId}")
                    null to batch.recipeId
                }
            }

            val template = PlannedSeriesItemEntity(
                seriesId = seriesId,
                foodId = foodId,
                recipeId = recipeId,
                grams = mi.grams,
                servings = mi.servings,
                note = null, // planned_items doesn't have note
                sortOrder = mi.sortOrder,
            )

            seriesItems.insert(template)
        }

        // Link anchor meal to series
        meals.update(meal.copy(seriesId = seriesId))

        Result(seriesId = seriesId, anchorDate = anchorDate)
    }
}
/**
 * =============================================================================
 * FOR FUTURE AI / FUTURE DEVELOPER — Series promotion invariants and evolution notes
 * =============================================================================
 *
 * Core invariant
 *
 * The anchor PlannedMealEntity defines the initial recurrence template.
 *
 * All template items MUST match anchor meal items exactly.
 *
 *
 * Why recipe batches are converted
 *
 * Batch IDs represent snapshot foods.
 *
 * They may be deleted or replaced.
 *
 * Recurrence must reference stable recipeId instead.
 *
 *
 * Anchor meal linkage
 *
 * PlannedMealEntity.seriesId marks the meal as belonging to the series.
 *
 * This allows:
 *
 * - editing single occurrence
 * - detecting recurrence membership
 * - future cancellation/override logic
 *
 *
 * Do NOT generate future occurrences here
 *
 * Occurrence expansion is intentionally separated to allow:
 *
 * - horizon-limited generation
 * - lazy expansion
 * - performance control
 *
 *
 * Schema dependencies
 *
 * Relies on:
 *
 * PlannedMealEntity
 * PlannedItemEntity
 * PlannedSeriesEntity
 * PlannedSeriesSlotRuleEntity
 * PlannedSeriesItemEntity
 *
 *
 * Migration caution
 *
 * Changing PlannedSeriesItemEntity schema requires updating this use case.
 *
 *
 * Recommended future improvement
 *
 * Add optional:
 *
 * copyNotes
 * copyOverrides
 *
 * if planned_items schema evolves.
 *
 *
 * Treat this as the canonical "promote meal to recurrence" entry point.
 */